### ISSUE TITLE
Project fails to build with `nuxt-prisma`

### ISSUE THREAD

**Issue by ohmree** [sidebase/nuxt-prisma#4] opened 2022-12-14 13:33 UTC
### Environment

Nuxi 3.0.0

RootDir: /tmp/test
Nuxt project info: 

------------------------------
- Operating System: `Linux`
- Node Version:     `v19.2.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `pnpm@7.18.2`
- Builder:          `vite`
- User Config:      `extends`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/ohmree/nuxt-prisma-repro

### Describe the bug

When building a nuxt app created with `pnpm dlx nuxi init <name>` and with the simplest `@sidebase/nuxt-prisma` config, it chokes on some of the `nuxt-prisma` code - seems like some rollup plugin tries to parse typescript as javascript.

### Logs

```console
$ pnpm build # this is run in the context of the linked reproduction repo

> @ build /tmp/test
> nuxt build

Nuxi 3.0.0
Nuxt 3.0.0 with Nitro 1.0.0
ℹ Client built in 997ms
ℹ Building server...
✔ Server built in 551ms
✔ Generated public .output/public
ℹ Building Nitro Server (preset: node-server)

 WARN  rollup-plugin-inject: failed to parse /tmp/test/node_modules/.pnpm/@sidebase+nuxt-prisma@0.1.0/node_modules/@sidebase/nuxt-prisma/nuxt-prisma/server/middleware/0.prisma.ts. Consider restricting the plugin to particular files via options.include


 ERROR 

2: import { eventHandler } from 'h3'
3: 
4: let prisma: PrismaClient
             ^
5: declare module 'h3' {
6:   interface H3EventContext {


 ERROR  Unexpected token (Note that you need plugins to import files that are not JavaScript)

  at error (node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
  at Module.error (node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:12429:16)
  at Module.tryParse (node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:12806:25)
  at Module.setSource (node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:12711:24)
  at ModuleLoader.addModuleSource (node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:21959:20)

 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by BracketJohn** [comment] 2022-12-17 11:58
Hey @ohmree 👋 

Thanks for reporting this - we'll look into it ASAP!

**Comment by BracketJohn** [comment] 2022-12-17 21:51
Oh, and btw: Thank you so much for providing a repro, verryyy helpful! 💯 ❤️

**Comment by BracketJohn** [comment] 2022-12-17 21:59
So, I tried to reproduce it by doing the following:
```
git clone https://github.com/ohmree/nuxt-prisma-repro
cd nuxt-prisma-repro

pnpm i
pnpm run build
```

and the error appeared.

The interesting part is: When I do it with `npm` the problem does not appear:
```
git clone https://github.com/ohmree/nuxt-prisma-repro
cd nuxt-prisma-repro

npm i
npm run build
```

Will further look into it, at the moment this problem seems to be `pnpm` specific.

**Comment by BracketJohn** [comment] 2022-12-18 18:11
Sorry, didn't mean to automatically close this issue via my commit -> reopening it while I'm testing whether the fix worked (:

**Comment by BracketJohn** [comment] 2023-01-05 11:51
Heya! 

We're actively persuing this:
- here's the possible underlying issue https://github.com/nuxt/framework/issues/9951
- here's the possible fix: https://github.com/nuxt/framework/issues/9951

Thanks @mannil for following through with this in our Discord convo -> amazing ❤️

**Comment by BracketJohn** [comment] 2023-01-10 13:06
Hey 🧇 

It turns out that sadly this is too much overhead to resolve - see #6 for problems that layers currently have. As this is a `lyaer` with just two files, we decided to instead directly integrate it into `create-sidebase` which resolves all of these problems and uses vanilla Nuxt, so if any of the problems occur we can be sure that they come from upstream.

Sorry for the bad news. We have a terminated, planned transition - read #6 for more. Let me know here if you need any specific help, I'd be happy to hop on a call to resolve your inidividual problem so that you still ahve a good experience with Nuxt + Prisma.

If you start a new project, I recommend that you use the cli like so:
```sh
# also works with yarn, pnpm
npm create sidebase@latest
```

to get prisma for free.

closing this, please add a new comment or ask something in #6 if it is related to the deprecation. Thanks ❤️

**Closed by BracketJohn** 2023-01-10 13:06 UTC
Labels: bug
